BaSP-Feature-MR154: Implement firebase members
BaSP-m2023/baru-megarocket-server pull request #100
Opened 2023-06-24 21:53 UTC by FontanR

Implement firebase in members

Now when create a new member we add a firebase id (in order to link to firebase data base). So we are using 2 data bases, 1 in mongo and 1 in firebase.

And now we cant edit neither mail or password from the edit endpoint (this functionality will be developed later when we add the email/password recovery)

2023-06-24 23:17 UTC, santimenendez98 requested changes

2023-06-24 23:17 UTC, santimenendez98 commented on src/controllers/member.js
> +  if (memberExists) {
This part is not needed as firebase already checks it

2023-06-24 23:17 UTC, santimenendez98 commented on src/models/Member.js
> +  firebaseUid: {
In this part to maintain consistency among all should be "fireBaseUid"

2023-06-25 14:23 UTC, santimenendez98 approved these changes

2023-06-25 18:03 UTC, IgnacioGalceran approved these changes

2023-06-25 18:24 UTC, merged