BaSP-MR-198: Classes validations
BaSP-m2023/baru-megarocket-server pull request #111
Opened 2023-07-03 23:25 UTC by jramire5

Classes:
-Added an available property, to check 
-Now it validates that the class has to start at an o'clock hour.
-Sunday is not anymore an elegible day.

2023-07-04 20:35 UTC, santimenendez98 approved these changes

2023-07-05 21:17 UTC, WalterArielPavicich requested changes

2023-07-05 21:17 UTC, WalterArielPavicich commented on src/validations/class.js
> +    subscribed: Joi.number().min(0).max(50).integer(),
if necessary, add that data is required

```suggestion
    subscribed: Joi.number().min(0).max(50).integer().required(),
```

2023-07-06 18:12 UTC, WalterArielPavicich approved these changes

2023-07-06 18:16 UTC, merged