BaSP-MR-04: update post-delete for the problem
BaSP-m2023/baru-megarocket-server pull request #59
Opened 2023-05-15 22:26 UTC by GinoLucci1

finish part post and delete, il wait for review and possible conflicts

2023-05-15 22:53 UTC, Bigzufi requested changes
You need to resolve the conflicts.

2023-05-16 03:05 UTC, Bigzufi commented on src/models/activity.js
The name of this file must be in PascalCase, so it has to be Activity.js

2023-05-16 03:12 UTC, Bigzufi commented on src/controllers/activity.js
As a suggestion, the response messages should follow the format given in the problem statement

2023-05-16 03:55 UTC, GinoLucci1 commented on src/models/activity.js
It is written like this in local, the change from lowercase to uppercase should appear in git

2023-05-16 12:31 UTC, Bigzufi approved these changes
Looks good to me

2023-05-16 18:44 UTC, merged