BaSP-MR-22: finish update and delete
BaSP-m2023/baru-megarocket-server pull request #76
Opened 2023-05-22 21:22 UTC by GinoLucci1

Finish this part of the weekly problem.

2023-05-22 21:51 UTC, maurojjzz requested changes

2023-05-22 21:51 UTC, maurojjzz commented on package.json
> +    "mongodb": "^5.5.0",
you should not modify package.json

2023-05-22 21:51 UTC, maurojjzz commented on package-lock.json
i dont know what you change in here but you shouldn't push it or change it

2023-05-22 22:16 UTC, Bigzufi commented
For my part, it looks good, once you have made the changes suggested by Mauro

2023-05-22 22:47 UTC, maurojjzz approved these changes
seems fine

2023-05-22 22:50 UTC, Bigzufi approved these changes
Looks good.

2023-05-23 20:39 UTC, BareaMartin approved these changes

2023-05-23 20:39 UTC, merged