BaSP-MR-88: Changes in admins resource
BaSP-m2023/baru-megarocket-server pull request #95
Opened 2023-06-13 23:33 UTC by WalterArielPavicich

https://trello.com/c/wVzOfV2M

Add response message when edit and add admins.
Changes in validations and admin model.

2023-06-13 23:42 UTC, francoax requested changes

2023-06-13 23:42 UTC, francoax commented on src/controllers/admins.js
> +      });
Try to add an `error` attribute in the response. This will be `error: false`

2023-06-13 23:42 UTC, francoax commented on src/controllers/admins.js
> +        });
Same here

2023-06-14 00:46 UTC, francoax approved these changes

2023-06-14 02:32 UTC, MauroCaffesse approved these changes

2023-06-14 02:37 UTC, merged