BaSP-MR-155: Trainer Server
BaSP-m2023/baru-megarocket-server pull request #98
Opened 2023-06-24 21:16 UTC by IgnacioGalceran

Changed functions in controller trainers, creating new trainer now creates a new user in firebase and mongodb. 
Changes in update controller function

2023-06-24 23:21 UTC, santimenendez98 requested changes

2023-06-24 23:21 UTC, santimenendez98 commented on src/models/Trainer.js
> +  firebaseUid: {
In this part to maintain consistency among all should be "fireBaseUid"

2023-06-25 17:32 UTC, FontanR commented on src/routes/index.js
> +const { default: verifyToken } = require('../middlewares/authMiddleware');
take out this too, please

2023-06-25 17:32 UTC, FontanR commented on src/routes/index.js
> +router.use('/trainer', verifyToken, trainers);
we agreed that routes will be implement in a separate ticket

2023-06-25 17:37 UTC, santimenendez98 approved these changes

2023-06-25 18:03 UTC, FontanR approved these changes
LGTM

2023-06-25 18:24 UTC, merged